### PR TITLE
remove stolen artwork

### PR DESCRIPTION
**Pull request by mrshmllow**
please stop using stolen artwork

### CODE REVIEW

**Comment by jmbuhr** [comment]
I assume you are referring to the fact that I used a diffusion model combined with hand-painting to generate parts of this image? I recognize the conflicting nature of how most of these have been trained, but this is not the place to have this discussion. Your contributions can have more impact elsewhere.

**Comment by mrshmllow** [comment]
please consider the impression that it gives of your project and to yourself. if you cant even be _bothered_ to create a thumbnail yourself then people wont be bothered to use your tool or watch your video. please respect artists

**Comment by jmbuhr** [comment]
I don't think you read my original reply correctly.

**Comment by zyriab** [comment]
image

**Comment by jmbuhr** [comment]
@zyriab I hope you don't mind me deleting your meme comment. I appreciate the support, but I don't want to pile on @mrshmllow with replies.

**Comment by jmbuhr** [comment]
In fact, let's handle it this way:

@mrshmllow While I don't agree with harassing individual creators that give away their work for free and your point seems slightly disingenuous coming from someone with a profile picture stolen from an Anime, I do agree on the general issue.

So, please shout out your favorite artist collectives or discussion groups fighting for the rights of artists against big corporations in this thread. This allows people to find meaningful ways of contributing to the cause. Afterwards, I will lock this conversation.

**Pull request closed without merging**
